baseURL = 'https://rematriate.net/'
languageCode = 'en-US'
title = 'The Rematriation Project'
logo = '/assets/images/logo.svg'

# BANNERS
# [[banners.nest]]
# h2 = "They have gathered together"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 30



[[menus.main]]
name = 'News'
pageRef = '/news'
weight = 40

[[menus.main]]
name = 'Tracing Rematriation'
pageRef = '/rema'
weight = 50

# [[menus.main]]
# name = 'Tags'
# pageRef = '/tags'
# weight = 50

[module]
  [module.hugoVersion]
    extended = false
    min = "0.126.3"
